//-------- APP CONTROLLERS ---------------
require('./app/controllers/RootController.js');
require('./app/controllers/HomeController.js');
require('./app/controllers/WorkspaceController.js');
require('./app/controllers/AdminDashboardController.js');
require('./app/controllers/EditorController.js');
require('./app/controllers/ImportController.js');
require('./app/controllers/SearchOrbitController.js');
require('./app/controllers/ValidateUserController.js');
require('./app/controllers/WasdiApplicationUIController.js');
require('./app/controllers/MarketPlaceController.js');
require('./app/controllers/WasdiApplicationDetailsController.js');

//-------- DIALOG CONTROLLERS ---------------
require('./app/dialogs/orbit_info/OrbitInfoController.js');
require("./app/dialogs/product_info/ProductInfoController.js");
require('./app/dialogs/get_capabilities_dialog/GetCapabilitiesController.js');
require('./app/dialogs/product_editor_info/ProductEditorInfoController.js');
require('./app/dialogs/attributes_metadata_info/AttributesMetadataController.js');
require('./app/dialogs/sftp_upload/SftpUploadController.js');
require('./app/dialogs/delete_process/DeleteProcessController.js');
require('./app/dialogs/workspace_processes_list/WorkspaceProcessesList.js');
require('./app/dialogs/snake_dialog/SnakeController.js');
require('./app/dialogs/downloadProductInWorkspace/DownloadProductInWorkspaceController.js');
require('./app/dialogs/import_advance_filters/ImportAdvanceFiltersController.js');
require('./app/dialogs/workflow_manager/WorkFlowManagerController.js');
require('./app/dialogs/style_manager/StyleManagerController.js');
require('./app/dialogs/style_edit/StyleController.js');
require('./app/dialogs/workflow_edit/WorkflowController.js');
require('./app/dialogs/get_list_of_workspace_selected/GetListOfWorkspacesSelectedController.js');
require('./app/dialogs/processor/ProcessorController.js');
require('./app/dialogs/workspace_details/WorkspaceDetailsController.js');
require('./app/dialogs/wapps/WappsController.js');
require('./app/dialogs/edit_user/EditUserController.js');
require('./app/dialogs/ftp_service/FTPController.js');
require('./app/dialogs/Import/UploadController.js');
require('./app/dialogs/mosaic/MosaicController.js');
require('./app/dialogs/processor_logs/ProcessorLogsController.js');
require('./app/dialogs/share_workspace/ShareWorkspaceController.js');
require('./app/dialogs/manual_insert_bbox/ManualInsertBboxController.js');
require('./app/dialogs/payload_dialog/PayloadDialogController.js');
require('./app/dialogs/processor_parameters_template/ProcessorParametersTemplateController.js');
require('./app/dialogs/send_feedback/SendFeedbackController.js');
require('./app/dialogs/package_manager/PackageManagerController.js')
require('./app/dialogs/processor_parameters_share/ProcessParamsShareController.js')
require('./app/dialogs/organization-edit/OrganizationEditorController.js'); 
require('./app/dialogs/org-users-edit/OrgUsersEditController.js'); 
require('./app/dialogs/share-organization/ShareOrganizationController.js'); 