FROM ubuntu:22.04


MAINTAINER "WASDI SARL"


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiSystemUserHome }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiSystemUserName }} && \
    mkdir --parents {{ sWasdiSoftwareRootDirectoryPath }} && \
    chown {{ sWasdiSoftwareRootDirectoryOwner }}:{{ sWasdiSoftwareRootDirectoryGroup }} {{ sWasdiSoftwareRootDirectoryPath }} && \
    chmod {{ sWasdiSoftwareRootDirectoryMode }} {{ sWasdiSoftwareRootDirectoryPath }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"          > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# RUN specific to install the JRE
RUN mkdir --parents {{ sWasdiJreRootDirectoryPath }} \
        {{ sWasdiJre8RootDirectoryPath }} \
        {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    chown {{ sWasdiJreRootDirectoryOwner }}:{{ sWasdiJreRootDirectoryGroup }} {{ sWasdiJreRootDirectoryPath }} && \
    chmod {{ sWasdiJreRootDirectoryMode }} {{ sWasdiJreRootDirectoryPath }} && \
    chown {{ sWasdiJre8RootDirectoryOwner }}:{{ sWasdiJre8RootDirectoryGroup }} {{ sWasdiJre8RootDirectoryPath }} && \
    chmod {{ sWasdiJre8RootDirectoryMode }} {{ sWasdiJre8RootDirectoryPath }} && \
    chown {{ sWasdiJre8RootDirectoryOwner }}:{{ sWasdiJre8RootDirectoryGroup }} {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    chmod {{ sWasdiJre8RootDirectoryMode }} {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    wget --no-verbose --show-progress --progress=bar:force:noscroll {{ sWasdiJre8SourceUrl }} --output-document /tmp/{{ sWasdiJre8SourceUrl | basename }} && \
    tar --extract --strip-components=1 --file /tmp/{{ sWasdiJre8SourceUrl | basename }} --directory {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    rm --force /tmp/{{ sWasdiJre8SourceUrl | basename }}

ENV JAVA_HOME="{{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }}"
ENV PATH="{{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }}/bin:${PATH}"


# From now, all commands executed are executed with the user 'root'
USER root


# RUN specific to Tomcat
RUN apt-get update && \
    apt-get install \
        libjhdf4-jni \
        libjhdf5-jni && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# RUN specific to install Tomcat
RUN mkdir --parents {{ sWasdiTomcatRootDirectoryPath }} \
        {{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }} && \
    chown {{ sWasdiTomcatRootDirectoryOwner }}:{{ sWasdiTomcatRootDirectoryGroup }} {{ sWasdiTomcatRootDirectoryPath }} && \
    chmod {{ sWasdiTomcatRootDirectoryMode }} {{ sWasdiTomcatRootDirectoryPath }} && \
    chown {{ sWasdiTomcatRootDirectoryOwner }}:{{ sWasdiTomcatRootDirectoryGroup }} {{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }} && \
    chmod {{ sWasdiTomcatRootDirectoryMode }} {{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }} && \
    wget --no-verbose --show-progress --progress=bar:force:noscroll {{ sWasdiTomcatSourceUrl }} --output-document /tmp/{{ sWasdiTomcatSourceUrl | basename }} && \
    tar --extract --strip-components=1 --file /tmp/{{ sWasdiTomcatSourceUrl | basename }} --directory {{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }} && \
    rm --force /tmp/{{ sWasdiTomcatSourceUrl | basename }}

ENV PATH="{{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }}/bin:${PATH}"


# Set the workdir
WORKDIR {{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }}


# Copy data
COPY --chown={{ sWasdiTomcatWebappsOgcProcessesServerTargetFileOwner }}:{{ sWasdiTomcatWebappsOgcProcessesServerTargetFileGroup }} ./dataToCopy/{{ sWasdiTomcatWebappsOgcProcessesServerTargetFileName }} {{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }}/webapps/{{ sWasdiTomcatWebappsOgcProcessesServerTargetFileName }}


# Start the container
CMD ["{{ sWasdiTomcatRootDirectoryPath }}/{{ sWasdiTomcatVersion }}/bin/catalina.sh", "run"]
