FROM ubuntu:22.04


MAINTAINER "WASDI SARL"


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"

# This variable is setted to set the default editor
ENV EDITOR="nano"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiSystemUserHome }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiSystemUserName }} && \
    mkdir --parents \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chown {{ sWasdiSoftwareRootDirectoryOwner }}:{{ sWasdiSoftwareRootDirectoryGroup }} \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chmod {{ sWasdiSoftwareRootDirectoryMode }} \
        {{ sWasdiSoftwareRootDirectoryPath }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"          > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# RUN specific to install the trigger
RUN apt-get update && \
    apt-get install \
        libjhdf4-jni \
        libjhdf5-jni && \
    mkdir --parents \
        {{ sWasdiDataPartitionRootDirectoryPath }} \
        {{ sWasdiDataRootDirectoryPath }} \
        {{ sWasdiDataConfigurationRootDirectoryPath }} \
        {{ sWasdiTriggerRootDirectoryPath }} && \
    chown {{ sWasdiDataPartitionRootDirectoryOwner }}:{{ sWasdiDataPartitionRootDirectoryGroup }} \
        {{ sWasdiDataPartitionRootDirectoryPath }} && \
    chmod {{ sWasdiDataPartitionRootDirectoryMode }} \
        {{ sWasdiDataPartitionRootDirectoryPath }} && \
    chown {{ sWasdiDataRootDirectoryOwner }}:{{ sWasdiDataRootDirectoryGroup }} \
        {{ sWasdiDataRootDirectoryPath }} && \
    chmod {{ sWasdiDataRootDirectoryMode }} \
        {{ sWasdiDataRootDirectoryPath }} && \
    chown {{ sWasdiDataConfigurationRootDirectoryOwner }}:{{ sWasdiDataConfigurationRootDirectoryGroup }} \
        {{ sWasdiDataConfigurationRootDirectoryPath }} && \
    chmod {{ sWasdiDataConfigurationRootDirectoryMode }} \
        {{ sWasdiDataConfigurationRootDirectoryPath }} && \
    chown {{ sWasdiTriggerRootDirectoryOwner }}:{{ sWasdiTriggerRootDirectoryGroup }} \
        {{ sWasdiTriggerRootDirectoryPath }} && \
    chmod {{ sWasdiTriggerRootDirectoryMode }} \
        {{ sWasdiTriggerRootDirectoryPath }} && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# RUN specific to install JRE 8
RUN mkdir --parents \
        {{ sWasdiJre8RootDirectoryPath }} \
        {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    chown {{ sWasdiJre8RootDirectoryOwner }}:{{ sWasdiJre8RootDirectoryGroup }} \
        {{ sWasdiJre8RootDirectoryPath }} \
        {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    chmod {{ sWasdiJre8RootDirectoryMode }} \
        {{ sWasdiJre8RootDirectoryPath }} \
        {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} && \
    wget \
        --no-verbose \
        --output-document /tmp/{{ sWasdiJre8SourceUrl | basename }} \
        --progress=bar:force:noscroll \
        --show-progress \
        {{ sWasdiJre8SourceUrl }} --output-document /tmp/{{ sWasdiJre8SourceUrl | basename }} && \
    tar \
        --directory {{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }} \
        --extract \
        --file /tmp/{{ sWasdiJre8SourceUrl | basename }} \
        --strip-components=1 && \
    rm --force \
        /tmp/{{ sWasdiJre8SourceUrl | basename }}

ENV JAVA_HOME="{{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }}"
ENV PATH="{{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }}/bin:${PATH}"


# Set the workdir
WORKDIR {{ sWasdiTriggerRootDirectoryPath }}


# Copy data
COPY --chown={{ sWasdiTriggerRootDirectoryOwner }}:{{ sWasdiTriggerRootDirectoryGroup }} ./dataToCopy/{{ sWasdiTriggerBuildTargetFileName }} {{ sWasdiTriggerRootDirectoryPath }}/{{ sWasdiTriggerBuildTargetFileName }}


# Start the container
ENTRYPOINT [ \
    "{{ sWasdiJre8RootDirectoryPath }}/{{ sWasdiJre8Version }}/bin/java", \
    "-Xmx24g", \
    "-Xms1024m", \
    "-XX:+AggressiveOpts", \
    "-Xverify:none", \
    "-jar", \
    "{{ sWasdiTriggerRootDirectoryPath }}/{{ sWasdiTriggerBuildTargetFileName }}", \
    "--config", \
    "{{ sWasdiDataConfigurationRootDirectoryPath }}/wasdiConfig.json", \
    "-scheduleid" \
]
