FROM ubuntu:22.04


LABEL org.opencontainers.image.authors="WASDI SARL"


# Labels used to search our containers and/or images
LABEL docker-image-name={{ sWasdiTomcatWasdiWebServerServiceName }}


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"

# This variable is setted to set the default editor
ENV EDITOR="nano"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiSystemUserHome }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiSystemUserName }} && \
    mkdir --parents \
        {{ sWasdiSystemUserHome }}/.ssh \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chown {{ sWasdiSystemUserName }}:{{ sWasdiSystemGroupName }} \
        {{ sWasdiSystemUserHome }}/.ssh && \
    chown {{ sWasdiSoftwareRootDirectoryOwner }}:{{ sWasdiSoftwareRootDirectoryGroup }} \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chmod 700 \
        {{ sWasdiSystemUserHome }}/.ssh && \
    chmod {{ sWasdiSoftwareRootDirectoryMode }} \
        {{ sWasdiSoftwareRootDirectoryPath }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"           > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    sed --in-place "s/# set tabsize.*/set tabsize 4/g" /etc/nanorc && \
    sed --in-place "s/# set tabstospaces/set tabstospaces/g" /etc/nanorc && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}

# RUN specific to install JDK 11
RUN mkdir --parents \
        {{ sWasdiJdk11RootDirectoryPath }} \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} && \
    chown {{ sWasdiJdk11RootDirectoryOwner }}:{{ sWasdiJdk11RootDirectoryGroup }} \
        {{ sWasdiJdk11RootDirectoryPath }} \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} && \
    chmod {{ sWasdiJdk11RootDirectoryMode }} \
        {{ sWasdiJdk11RootDirectoryPath }} \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} && \
    wget \
        --no-verbose \
        --output-document /tmp/{{ sWasdiJdk11SourceUrl | basename }} \
        --progress=bar:force:noscroll \
        --show-progress \
        {{ sWasdiJdk11SourceUrl }} && \
    tar \
        --directory {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} \
        --extract \
        --file /tmp/{{ sWasdiJdk11SourceUrl | basename }} \
        --strip-components=1 && \
    ln \
        --symbolic \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} \
        {{ sWasdiJdk11RootDirectoryPath }}/latest && \
    chown --no-dereference {{ sWasdiJdk11RootDirectoryOwner }}:{{ sWasdiJdk11RootDirectoryGroup }} \
        {{ sWasdiJdk11RootDirectoryPath }}/latest && \
    rm --force \
        /tmp/{{ sWasdiJdk11SourceUrl | basename }}

ENV JAVA_HOME="{{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }}"
ENV PATH="{{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }}/bin:${PATH}"

# From now, all commands executed are executed with the user 'root'
USER root


# RUN specific to Tomcat
RUN mkdir --parents \
        {{ sWasdiMountedVolumeRootDirectoryPath }} \
        {{ sWasdiMountedUserVolumeRootDirectoryPath }} && \
    chown {{ sWasdiMountedVolumeRootDirectoryOwner }}:{{ sWasdiMountedVolumeRootDirectoryGroup }} {{ sWasdiMountedVolumeRootDirectoryPath }} && \
    chmod {{ sWasdiMountedVolumeRootDirectoryMode }} {{ sWasdiMountedVolumeRootDirectoryPath }} && \
    chown {{ sWasdiMountedUserVolumeRootDirectoryOwner }}:{{ sWasdiMountedUserVolumeRootDirectoryGroup }} {{ sWasdiMountedUserVolumeRootDirectoryPath }} && \
    chmod {{ sWasdiMountedUserVolumeRootDirectoryMode }} {{ sWasdiMountedUserVolumeRootDirectoryPath }} && \
    apt-get update && \
    apt-get install \
        libjhdf4-jni \
        libjhdf5-jni && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# RUN specific to install Tomcat
RUN mkdir --parents \
        {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }} \
        {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }} && \
    chown {{ sWasdiTomcatWasdiWebServerRootDirectoryOwner }}:{{ sWasdiTomcatWasdiWebServerRootDirectoryGroup }} \
        {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }} \
        {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }} && \
    chmod {{ sWasdiTomcatWasdiWebServerRootDirectoryMode }} \
        {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }} \
        {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }} && \
    wget \
        --no-verbose \
        --output-document /tmp/{{ sWasdiTomcatWasdiWebServerSourceUrl | basename }} \
        --progress=bar:force:noscroll \
        --show-progress \
        {{ sWasdiTomcatWasdiWebServerSourceUrl }} && \
    tar \
        --directory {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }} \
        --extract \
        --file /tmp/{{ sWasdiTomcatWasdiWebServerSourceUrl | basename }} \
        --strip-components=1 && \
    rm --recursive --force \
      /tmp/{{ sWasdiTomcatWasdiWebServerSourceUrl | basename }} \
      {{ sWasdiTomcatWasdiWebServerRootDirectoryMode }} {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/webapps/ROOT \
      {{ sWasdiTomcatWasdiWebServerRootDirectoryMode }} {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/webapps/docs \
      {{ sWasdiTomcatWasdiWebServerRootDirectoryMode }} {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/webapps/examples && \
    sed --in-place 's/127\\.\\d+\\.\\d+\\.\\d+/127\\.\\d+\\.\\d+\\.\\d+|{{ sWasdiDockerNetworkRange.split('.')[0] }}\\.{{ sWasdiDockerNetworkRange.split('.')[1] }}\\.\\d+\\.\\d+/g' {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/webapps/manager/META-INF/context.xml
ENV TOMCAT_HOME="{{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}"
ENV PATH="{{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/bin:${PATH}"


# Set the workdir
WORKDIR {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}


# Copy data
COPY --chown={{ sWasdiTomcatWasdiWebServerBuildTargetFileOwner }}:{{ sWasdiTomcatWasdiWebServerBuildTargetFileGroup }} ./dataToCopy/{{ sWasdiTomcatWasdiWebServerBuildTargetFileName }} {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/webapps/{{ sWasdiTomcatWasdiWebServerBuildTargetFileName }}
COPY --chown={{ sWasdiSystemUserName }}:{{ sWasdiSystemGroupName }} ./dataToCopy/conf_server.xml {{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/conf/server.xml
COPY --chown={{ sWasdiSystemUserName }}:{{ sWasdiSystemGroupName }} ./dataToCopy/docker-entrypoint.sh /docker-entrypoint.sh


# Start the container
ENTRYPOINT ["/bin/bash", "/docker-entrypoint.sh"]
CMD [ \
    "{{ sWasdiTomcatWasdiWebServerRootDirectoryPath }}/{{ sWasdiTomcatWasdiWebServerVersion }}/bin/catalina.sh", \
    "run" \
]
