FROM ubuntu:22.04


LABEL org.opencontainers.image.authors="WASDI SARL"


# Labels used to search our containers and/or images
LABEL docker-image-name={{ sWasdiRabbitMqServiceName }}


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"

# This variable is setted to set the default editor
ENV EDITOR="nano"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiRabbitMqSystemGroupName }} && \
    useradd --create-home --home-dir /home/{{ sWasdiRabbitMqSystemUserName }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiRabbitMqSystemUserName }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"          > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    sed --in-place "s/# set tabsize.*/set tabsize 4/g" /etc/nanorc && \
    sed --in-place "s/# set tabstospaces/set tabstospaces/g" /etc/nanorc && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# RUN specific to install RabbitMQ
RUN apt-get update && \
    apt-get install \
        rabbitmq-server && \
    mkdir --parents \
        /var/log/rabbitmq \
        /var/run/rabbitmq && \
    chmod 770 \
        /etc/rabbitmq \
        /var/log/rabbitmq \
        /var/run/rabbitmq && \
    chown --recursive {{ sWasdiRabbitMqSystemUserName }}:{{ sWasdiRabbitMqSystemGroupName }} \
        /etc/rabbitmq \
        {{ sWasdiRabbitMqBaseDirectoryPath }} \
        /var/log/rabbitmq/ \
        /var/run/rabbitmq/ && \
    rm --force /etc/rabbitmq/rabbitmq-env.conf && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiRabbitMqSystemUserName }}'
USER {{ sWasdiRabbitMqSystemUserName }}


# Set the workdir
WORKDIR /home/{{ sWasdiRabbitMqSystemUserName }}


# Copy data
COPY --chown={{ sWasdiRabbitMqSystemUserName }}:{{ sWasdiRabbitMqSystemGroupName }} ./dataToCopy/etc_rabbitmq_rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY --chown={{ sWasdiRabbitMqSystemUserName }}:{{ sWasdiRabbitMqSystemGroupName }} ./dataToCopy/docker-entrypoint.sh /docker-entrypoint.sh
COPY --chown={{ sWasdiRabbitMqSystemUserName }}:{{ sWasdiRabbitMqSystemGroupName }} ./dataToCopy/advanced.config /etc/rabbitmq/advanced.config


# Start the container
ENTRYPOINT ["/bin/bash", "/docker-entrypoint.sh"]
CMD [ \
    "/usr/lib/rabbitmq/bin/rabbitmq-server" \
]
