FROM ubuntu:22.04


LABEL org.opencontainers.image.authors="WASDI SARL"


# Labels used to search our containers and/or images
LABEL docker-image-name={{ sWasdiUtilsServiceName }}


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"

# This variable is setted to set the default editor
ENV EDITOR="nano"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiSystemUserHome }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiSystemUserName }} && \
    mkdir --parents \
        {{ sWasdiSystemUserHome }}/.ssh \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chown {{ sWasdiSystemUserName }}:{{ sWasdiSystemGroupName }} \
        {{ sWasdiSystemUserHome }}/.ssh && \
    chown {{ sWasdiSoftwareRootDirectoryOwner }}:{{ sWasdiSoftwareRootDirectoryGroup }} \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chmod 700 \
        {{ sWasdiSystemUserHome }}/.ssh && \
    chmod {{ sWasdiSoftwareRootDirectoryMode }} \
        {{ sWasdiSoftwareRootDirectoryPath }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"           > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    sed --in-place "s/# set tabsize.*/set tabsize 4/g" /etc/nanorc && \
    sed --in-place "s/# set tabstospaces/set tabstospaces/g" /etc/nanorc && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# RUN specific to install the Utils
RUN apt-get update && \
    mkdir --parents \
        {{ sWasdiConfigurationRootDirectoryPath }} \
        {{ sWasdiUtilsRootDirectoryPath }} && \
    chown {{ sWasdiConfigurationRootDirectoryOwner }}:{{ sWasdiConfigurationRootDirectoryGroup }} \
        {{ sWasdiConfigurationRootDirectoryPath }} && \
    chmod {{ sWasdiConfigurationRootDirectoryMode }} \
        {{ sWasdiConfigurationRootDirectoryPath }} && \
    chown {{ sWasdiUtilsRootDirectoryOwner }}:{{ sWasdiUtilsRootDirectoryGroup }} \
        {{ sWasdiUtilsRootDirectoryPath }} && \
    chmod {{ sWasdiUtilsRootDirectoryMode }} \
        {{ sWasdiUtilsRootDirectoryPath }} && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# RUN specific to install JDK 11
RUN mkdir --parents \
        {{ sWasdiJdk11RootDirectoryPath }} \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} && \
    chown {{ sWasdiJdk11RootDirectoryOwner }}:{{ sWasdiJdk11RootDirectoryGroup }} \
        {{ sWasdiJdk11RootDirectoryPath }} \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} && \
    chmod {{ sWasdiJdk11RootDirectoryMode }} \
        {{ sWasdiJdk11RootDirectoryPath }} \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} && \
    wget \
        --no-verbose \
        --output-document /tmp/{{ sWasdiJdk11SourceUrl | basename }} \
        --progress=bar:force:noscroll \
        --show-progress \
        {{ sWasdiJdk11SourceUrl }} && \
    tar \
        --directory {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} \
        --extract \
        --file /tmp/{{ sWasdiJdk11SourceUrl | basename }} \
        --strip-components=1 && \
    ln \
        --symbolic \
        {{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }} \
        {{ sWasdiJdk11RootDirectoryPath }}/latest && \
    chown --no-dereference {{ sWasdiJdk11RootDirectoryOwner }}:{{ sWasdiJdk11RootDirectoryGroup }} \
        {{ sWasdiJdk11RootDirectoryPath }}/latest && \
    rm --force \
        /tmp/{{ sWasdiJdk11SourceUrl | basename }}

ENV JAVA_HOME="{{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }}"
ENV PATH="{{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }}/bin:${PATH}"


# Set the workdir
WORKDIR {{ sWasdiUtilsRootDirectoryPath }}


# Copy data
COPY --chown={{ sWasdiUtilsRootDirectoryOwner }}:{{ sWasdiUtilsRootDirectoryGroup }} ./dataToCopy/{{ sWasdiUtilsBuildTargetFileName }} {{ sWasdiUtilsRootDirectoryPath }}/{{ sWasdiUtilsBuildTargetFileName }}


# Start the container
CMD [ \
    "{{ sWasdiJdk11RootDirectoryPath }}/{{ sWasdiJdk11Version }}/bin/java", \
    "-Xmx24g", \
    "-Xms1024m", \
    "-XX:+AggressiveOpts", \
    "-Xverify:none", \
    "-jar", \
    "{{ sWasdiUtilsRootDirectoryPath }}/{{ sWasdiUtilsBuildTargetFileName }}", \
    "--config", \
    "{{ sWasdiConfigurationRootDirectoryPath }}/wasdiConfig.json" \
]
