FROM ubuntu:22.04


LABEL org.opencontainers.image.authors="WASDI SARL"


# Labels used to search our containers and/or images
LABEL docker-image-name={{ sWasdiSnaphuServiceName }}


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"

# This variable is setted to set the default editor
ENV EDITOR="nano"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiSystemUserHome }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiSystemUserName }} && \
    mkdir --parents \
        {{ sWasdiSystemUserHome }}/.ssh \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chown {{ sWasdiSystemUserName }}:{{ sWasdiSystemGroupName }} \
        {{ sWasdiSystemUserHome }}/.ssh && \
    chown {{ sWasdiSoftwareRootDirectoryOwner }}:{{ sWasdiSoftwareRootDirectoryGroup }} \
        {{ sWasdiSoftwareRootDirectoryPath }} && \
    chmod 700 \
        {{ sWasdiSystemUserHome }}/.ssh && \
    chmod {{ sWasdiSoftwareRootDirectoryMode }} \
        {{ sWasdiSoftwareRootDirectoryPath }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"          > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    sed --in-place "s/# set tabsize.*/set tabsize 4/g" /etc/nanorc && \
    sed --in-place "s/# set tabstospaces/set tabstospaces/g" /etc/nanorc && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# RUN specific to install Snaphu
RUN mkdir --parents \
    {{ sWasdiSnaphuRootDirectoryPath }} && \
    chown {{ sWasdiSnaphuRootDirectoryOwner }}:{{ sWasdiSnaphuRootDirectoryGroup }} \
        {{ sWasdiSnaphuRootDirectoryPath }} && \
    chmod {{ sWasdiSnaphuRootDirectoryMode }} \
        {{ sWasdiSnaphuRootDirectoryPath }} && \
    wget \
        --no-verbose \
        --output-document=/tmp/{{ sWasdiSnaphuSourceUrl | basename }} \
        --progress=bar:force:noscroll \
        --show-progress \
        {{ sWasdiSnaphuSourceUrl }} && \
    unzip \
        /tmp/{{ sWasdiSnaphuSourceUrl | basename }} \
        -d {{ sWasdiSnaphuRootDirectoryPath }}/ && \
    mv {{ sWasdiSnaphuRootDirectoryPath }}/snaphu-v{{ sWasdiSnaphuVersion }}_linux {{ sWasdiSnaphuRootDirectoryPath }}/{{ sWasdiSnaphuVersion }} && \
    rm --force /tmp/{{ sWasdiSnaphuSourceUrl | basename }}

ENV PATH="{{ sWasdiSnaphuRootDirectoryPath }}/{{ sWasdiSnaphuVersion }}/bin:${PATH}"


# Set the workdir
WORKDIR {{ sWasdiSnaphuRootDirectoryPath }}/{{ sWasdiSnaphuVersion }}


# Default ENTRYPOINT and COMMAND
ENTRYPOINT ["snaphu"]
CMD ["--help"]
