FROM ubuntu:22.04


MAINTAINER "WASDI SARL"


# From now, all commands executed are executed with the user 'root'
USER root


# This environment variable is setted to avoid packages to ask a confirmation
ENV DEBIAN_FRONTEND="noninteractive"

# This variable is setted to make Python stop creating files '.pyc'
ENV PYTHONDONTWRITEBYTECODE="False"

# This variable is setted to force the 'print' method of Python to flush message directly
ENV PYTHONUNBUFFERED="True"


# RUN generic to create user, group, directories, etc
RUN groupadd --gid {{ sWasdiSystemGroupId }} --non-unique {{ sWasdiSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiSystemUserHome }} --uid {{ sWasdiSystemUserId }} --gid {{ sWasdiSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiSystemUserName }} && \
    mkdir --parents {{ sWasdiSoftwareRootDirectoryPath }} && \
    chown {{ sWasdiSoftwareRootDirectoryOwner }}:{{ sWasdiSoftwareRootDirectoryGroup }} {{ sWasdiSoftwareRootDirectoryPath }} && \
    chmod {{ sWasdiSoftwareRootDirectoryMode }} {{ sWasdiSoftwareRootDirectoryPath }}


# RUN generic to update the system and install common packages
RUN echo "APT::Install-Suggests \"0\";" > /etc/apt/apt.conf.d/99local && \
    echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Get::Assume-Yes \"true\";" >> /etc/apt/apt.conf.d/99local && \
    echo "APT::Keep-Downloaded-Packages \"false\";" >> /etc/apt/apt.conf.d/99local && \
    echo "Dpkg::Options::--force-confold;" >> /etc/apt/apt.conf.d/99local && \
    apt-get update && \
    apt-get install \
        ca-certificates && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy main restricted universe multiverse"          > /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-updates main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirror.ubuntu.ikoula.com/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get dist-upgrade && \
    apt-get install \
        curl \
        nano \
        tar \
        unzip \
        wget && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# RUN specific to install all elements related to the toolbox
RUN groupadd --gid {{ sWasdiBackupSystemGroupId }} --non-unique {{ sWasdiBackupSystemGroupName }} && \
    useradd --create-home --home-dir {{ sWasdiBackupSystemUserHome }} --uid {{ sWasdiBackupSystemUserId }} --gid {{ sWasdiBackupSystemGroupId }} --non-unique --shell /bin/bash {{ sWasdiBackupSystemUserName }} && \
    apt-get update && \
    apt-get install \
        gpg && \
    curl --fail --silent --show-error --location https://pgp.mongodb.com/server-4.4.asc | gpg --dearmor --output /usr/share/keyrings/mongodb-server-4.4.gpg && \
    curl --fail --silent --show-error --location https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor --output /usr/share/keyrings/postgresql.gpg && \
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" > /etc/apt/sources.list.d/mongodb-org-4.4.list && \
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/postgresql.gpg ] https://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/postgresql.list && \
    apt-get update && \
    apt-get install \
        iputils-ping \
        git \
        mongodb-org-tools \
        postgresql-client-15 \
        python3 \
        python3-pip \
        python3-psycopg2 \
        python3-venv && \
    rm --recursive --force /var/lib/apt/lists/* && \
    find / -xdev -type d -name __pycache__ -exec rm --recursive --force {} +


# From now, all commands executed are executed with the user '{{ sWasdiSystemUserName }}'
USER {{ sWasdiSystemUserName }}


# Update the ${PATH} variable to be able to call the PostgreSQL binaries
ENV PATH="${PATH}:/usr/lib/postgresql/14/bin"


# RUN specific to install all elements related to the toolbox
RUN mkdir --parents {{ sWasdiToolboxRootDirectoryPath }} \
        {{ sWasdiToolboxRootDirectoryPath }}/code \
        {{ sWasdiToolboxRootDirectoryPath }}/configuration \
        {{ sWasdiToolboxRootDirectoryPath }}/output \
        {{ sWasdiToolboxRootDirectoryPath }}/template \
        {{ sWasdiToolboxRootDirectoryPath }}/temporary \
        {{ sWasdiToolboxRootDirectoryPath }}/pythonVirtualEnvironment && \
    chmod 755 {{ sWasdiToolboxRootDirectoryPath }} \
        {{ sWasdiToolboxRootDirectoryPath }}/code \
        {{ sWasdiToolboxRootDirectoryPath }}/configuration \
        {{ sWasdiToolboxRootDirectoryPath }}/output \
        {{ sWasdiToolboxRootDirectoryPath }}/template \
        {{ sWasdiToolboxRootDirectoryPath }}/temporary \
        {{ sWasdiToolboxRootDirectoryPath }}/pythonVirtualEnvironment && \
    chmod 777 {{ sWasdiToolboxRootDirectoryPath }} \
        {{ sWasdiToolboxRootDirectoryPath }}/template \
        {{ sWasdiToolboxRootDirectoryPath }}/temporary && \
    python3 -m venv --system-site-packages {{ sWasdiToolboxRootDirectoryPath }}/pythonVirtualEnvironment && \
    {{ sWasdiToolboxRootDirectoryPath }}/pythonVirtualEnvironment/bin/pip3 install --no-cache-dir --no-compile \
        ConfigArgParse \
        jinja2 \
        prettytable \
        pymongo


# Set the workdir
WORKDIR {{ sWasdiToolboxRootDirectoryPath }}/code


# Copy data
COPY --chown=appwasdi:appwasdi ./dataToCopy/code/ {{ sWasdiToolboxRootDirectoryPath }}/code/


# ENTRYPOINT
ENTRYPOINT [ \
    "{{ sWasdiToolboxRootDirectoryPath }}/pythonVirtualEnvironment/bin/python3", \
    "{{ sWasdiToolboxRootDirectoryPath }}/code/toolbox.py", \
    "--log-on-screen", \
    "--configuration-directory", \
    "{{ sWasdiToolboxRootDirectoryPath }}/configuration" \
]
