version: "3.7"

networks:
  default:
    external:
      name: "wasdi-network"

services:
  traefik-notebook:
    image: "traefik:v2.10.3"
    container_name: "traefik-notebook"
    restart: "unless-stopped"
    user: "root:root"
    stdin_open: true
    tty: true
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--log.format=common"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik/conf.d"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
    ports:
{% if ( companyServiceName | lower ) in ["computationalnode003"] %}
      - "127.0.0.1:8083:80"
{% elif ( companyEnvironmentName | lower ) in ["test"] and ( companyServiceName | lower ) in ["mainnode002"] %}
      - "127.0.0.1:8083:80"
{% else %}
      - "8083:80"
{% endif %}
    volumes:
      - "{{ sWasdiDataDockerVolumeRootDirectoryPath }}/traefik-notebook/etc_traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
