version: "3.7"

networks:
  default:
    external:
      name: "wasdi-network"

services:
  traefik-notebook:
    image: "traefik:v2.8.1"
    container_name: "traefik-notebook"
    restart: "unless-stopped"
    user: "root:root"
    stdin_open: true
    tty: true
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik/conf.d"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
    ports:
      - "9000:80"
    volumes:
      - "/data/wasdi/container/volume/traefik-notebook/etc_traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
