FROM wasdi-launcher-base:latest


MAINTAINER "WASDI SARL"


# Set the workdir
WORKDIR {{ sWasdiLauncherRootDirectoryPath }}


# Copy data
COPY --chown={{ sWasdiLauncherRootDirectoryOwner }}:{{ sWasdiLauncherRootDirectoryGroup }} ./dataToCopy/{{ sWasdiLauncherBuildTargetFileName }} {{ sWasdiLauncherRootDirectoryPath }}/{{ sWasdiLauncherBuildTargetFileName }}
