FROM wasdi-base-launcher:latest


MAINTAINER "WASDI SARL"


# Labels used to search our containers and/or images
LABEL docker-image-name={{ sWasdiLauncherServiceName }}


# Set the workdir
WORKDIR {{ sWasdiLauncherRootDirectoryPath }}


# Copy data
COPY --chown={{ sWasdiLauncherRootDirectoryOwner }}:{{ sWasdiLauncherRootDirectoryGroup }} ./dataToCopy/{{ sWasdiLauncherBuildTargetFileName }} {{ sWasdiLauncherRootDirectoryPath }}/{{ sWasdiLauncherBuildTargetFileName }}
