FROM python:3.8-alpine


RUN mkdir --parents \
    /usr/src/app \
    /usr/src/app/docs \
    /usr/src/app/build \
    /usr/src/libraries/jswasdilib && \
  pip install --no-cache-dir \
    sphinx==3.5.4 \
    sphinx-rtd-theme==0.5.2 \
    javasphinx==0.9.15 \
    sphinxemoji==0.1.8 \
    sphinxcontrib-matlabdomain==0.11.8 \
    myst_parser==0.17.2 \
    sphinx-js==3.1.2 \
    MarkupSafe==2.0.1 \
    sphinxcontrib-youtube==1.2.0 && \
  apk add --update nodejs npm && \
  npm install -g typedoc@0.22.18


WORKDIR /usr/src/app


## still need to fix domain.py for javasphinx :-( 
COPY ./domain.py /usr/local/lib/python3.8/site-packages/javasphinx/domain.py


# Start the container
ENTRYPOINT [ \
    "sphinx-build", \
    "-M", \
    "html", \
    "/usr/src/app/docs", \
    "build" \
]