FROM python:3.12-alpine


RUN mkdir --parents \
    /usr/src/app \
    /usr/src/app/docs \
    /usr/src/app/build \
    /usr/src/libraries/jswasdilib && \
  pip install --no-cache-dir \
    sphinx==7.2.6 \
    sphinx-rtd-theme==2.0.0 \
    javasphinx==0.9.15 \
    sphinxemoji==0.3.1 \
    sphinxcontrib-matlabdomain==0.21.5 \
    sphinx-js==3.2.2 \
    MarkupSafe==2.0.1 \
    sphinxcontrib-youtube==1.4.1 && \
  apk add --update nodejs npm && \
  npm install -g jsdoc@3.6.10

## still need to fix domain.py for javasphinx :-( 
COPY ./docs/domain.py /usr/local/lib/python3.12/site-packages/javasphinx/domain.py

#RUN pwd
WORKDIR /usr/src/app

# Start the container
ENTRYPOINT [ \
    "sphinx-build", \
    "-M", \
    "html", \
    "/usr/src/app/docs", \
    "build" \
]